DROP TABLE IF EXISTS `players`;
CREATE TABLE `players` 
(
    `guid` BIGINT UNSIGNED NOT NULL,
    `entry` INT UNSIGNED NOT NULL,
    `username` VARCHAR(20) NOT NULL,
    `password` VARCHAR(30) NOT NULL,
    `email` VARCHAR(40) NOT NULL,
    `x` SMALLINT UNSIGNED NOT NULL,
    `y` SMALLINT UNSIGNED NOT NULL,
    `map` INT UNSIGNED NOT NULL,
    PRIMARY KEY(guid)
);

DROP TABLE IF EXISTS `creature`;
CREATE TABLE `creature` 
(
    `guid` BIGINT UNSIGNED NOT NULL,
    `entry` INT UNSIGNED NOT NULL,
    `x` SMALLINT UNSIGNED NOT NULL,
    `y` SMALLINT UNSIGNED NOT NULL,
    `map` INT UNSIGNED NOT NULL,
    PRIMARY KEY(guid)
);

DROP TABLE IF EXISTS `maps`;
CREATE TABLE `maps` 
(
    `guid` BIGINT UNSIGNED NOT NULL,
    `name` VARCHAR(20) NOT NULL,
    `width` SMALLINT UNSIGNED NOT NULL,
    `height` SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY(guid)
);
